services:
  postgres:
    image: postgres:16
    container_name: climbing-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPRING_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: